### ISSUE TITLE
Possibility to add redirect_uri to refresh token endpoint

### ISSUE THREAD

**Issue by Sholofly** [travisghansen/external-auth-server#104]
Hi,

I am trying to implement this to be able to consume the [Geocaching API](https://api.groundspeak.com/documentation#authorization). Their approach is almost completely following the oAut2 specification. The only thing that is different is that for renewing the token with the refresh_token, you also need to pass the redirect_uri as a parameter. Its just for validation, you will not be redirected during the refresh action. Is there a possibility for me to implement that behavior in your server using the config options?

**Comment by travisghansen** [comment]
I may already have this available in my `next` branch but let me confirm. To be clear you just want to set some static value in the request right?

**Comment by Sholofly** [comment]
Yeah, in my case it's the original redirect_uri that was used in the inital auth sequence.

**Comment by travisghansen** [comment]
Just landed it in `next` here: https://github.com/travisghansen/external-auth-server/commit/8950e40008652ae412c32adb8b45c0a007141156

`next` images have been built and are ready to test.

In the plugin config add `custom_refresh_parameters: { redirect_uri: <your uri>}` and let me know how it goes.

- https://github.com/travisghansen/external-auth-server/blob/next/PLUGINS.md

**Comment by Sholofly** [comment]
That's cool! I just don;t know how tor un your branch in my docker. Can you help me with that?

**Comment by travisghansen** [comment]
Are you trying to edit files so you can generate the token?

**Comment by Sholofly** [comment]
> Are you trying to edit files so you can generate the token?

Yes!

**Comment by travisghansen** [comment]
Ah, maybe execute the old (`latest`) container just to create the token?

**Comment by travisghansen** [comment]
Any luck?

**Comment by Sholofly** [comment]
Thanks for the follow up!

Yeah, I've managed to get it running but haven't tested it. At midnight I
was able to get to the external API using my server. But I am not able to
whitelist my redirect uri there myself.

Against all odds today I received permission from Home Assistant to use
their cloud for accessing the geocaching API. That's making your project
obsolete for my current project. I really want to test your application for
other projects I am thinking about, but I need time to finish my current
project first.

I really appreciate your quick support, and when time is ready I will get
back to your project.

Thanks!

Op wo 31 mrt. 2021 17:06 schreef Travis Glenn Hansen <
***@***.***>:

**Comment by travisghansen** [comment]
Ok should we close this for now and reopen if it doesn’t work when you try to use it?

**Comment by Sholofly** [comment]
Yes!
