### ISSUE TITLE
[OIDC] TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by kevinoconnor7** [travisghansen/external-auth-server#107]
Since upgrading to `v0.10.0` EAS is failing to authenticate sessions with the error:

```
TypeError: Cannot read property 'split' of undefined
    at OpenIdConnectPlugin.prepare_authentication_data (/home/eas/app/src/plugin/oauth/index.js:1935:61)
    at OpenIdConnectPlugin.verify (/home/eas/app/src/plugin/oauth/index.js:1609:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async processPipeline (/home/eas/app/src/server.js:367:13)
```

Looks like this is from 8950e40008652ae412c32adb8b45c0a007141156. Let me know if you need more information about my particular configuration!

**Comment by travisghansen** [comment]
Fix coming shortly. I guess that property isn't sent by all providers. Who is your issuer out of curiosity?

**Comment by kevinoconnor7** [comment]
AWS Cognito

**Comment by travisghansen** [comment]
Images building now.. https://github.com/travisghansen/external-auth-server/actions

Sorry for the mixup and thanks for the report!

**Comment by travisghansen** [comment]
I added a *bunch* of logout features in this last release for `oidc` including `backchannel` support as an FYI.

Fix is `v0.10.2`.

**Comment by travisghansen** [comment]
Looks like images are built. Try it out and let me know how it goes.

**Comment by kevinoconnor7** [comment]
Works great! Thanks for the quick fix!
