### ISSUE TITLE
Setting up traefix, eas and keycloak trows the error "unable to verify the first certificate"

### ISSUE THREAD

**Issue by tverhoeven** [travisghansen/external-auth-server#11]
I really like the concept of eas and how easy it makes to integrate security for different k8s apps that we will run. So I'm trying to set it up.

I'm using GKS with traefik as my ingress handler. I've been successful in setting up my apps, traefik and eas using basic auth as a first test. This setup works fine.

The final step that I want to take is to add keycloak to the setup. So I have also deployed keycloak into my GKS cluster. I've configured a realm and a client and created config_token.

When I now test the token I get a 503 error back from eas. Looking in the log I see this error:

code: "UNABLE_TO_VERIFY_LEAF_SIGNATURE"   
  level: "error"   
  message: "unable to verify the first certificate"   
  service: "external-auth-server"   
  stack: "Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1055:34)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket._finishInit (_tls_wrap.js:633:8)"   

traefik is configured with a TLS wildcard cert for the domain I'm using. The cert works fine in Firefox and Chrome (it a cert issued by godaddy). Both, the apps, eas and keycloak are using a domain covered by the wildcard cert.

What could be going wrong here? Do I need to give a CA to eas, but I don't see how to configure it.

**Comment by travisghansen** [comment]
Awesome! Glad you're finding it useful

I'm going to have to look into this one. I'm guessing it's coming from hitting the discovery URL?

In the mean time, try to exec into the container and use curl/wget (not sure if they're installed in the container) to hit the discover url manually and see what you get.

**Comment by travisghansen** [comment]
Likely what's going on..

https://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

I'll add that package and support to inject custom CAs somehow...either at the server level or at the token level or both. One of my line items for the next release was to support self-signed certs so this is right down that path generally.

**Comment by tverhoeven** [comment]
Thank you for the feedback. The error in the logs don't really say if it is from the discovery URL. But that is also what I assume.

I did run curl with some verbose options inside the container and this is the relevant part of the output:

```
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: OU=Domain Control Validated; CN=*.dataroots.io
*  start date: Mar 19 10:06:40 2019 GMT
*  expire date: Mar 19 09:10:13 2021 GMT
*  issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
```

Testing a Google URL works fine. So it looks like the base Linux image that you use does not have the CA certs from GoDaddy included (or a older version). Maybe refresh the base OS or something?

**Comment by tverhoeven** [comment]
Good news. I've made progress. I followed the statement here : https://git.coolaj86.com/coolaj86/ssl-root-cas.js#important-try-this-first

I've added the intermediate cert to my own cert and recreated the secret used by traefik. With this cert bundle the issue is resolved. Both curl and eas itself will now accept the cert and continue.

So issue solved and I can now continue testing.

**Comment by travisghansen** [comment]
I was wondering about that.. I'll take a look at the other solution regardless and get something more robust implemented.

Couple other tips for going to prod with it:

1. I'd suggest server-side tokens if you'll have the same config used on several services.
1. If you plan on doing SSO type stuff with openid I highly suggest setting the config token `aud` value. I need to write up a bit more on this but I'll put another comment here when back at my desk with more details.

**Comment by travisghansen** [comment]
After reading through the doc and reviewing I've integrated the ability to set custom CAs in the chart that will be injected via the `NODE_EXTRA_CA_CERTS` environment variable. Good enough for now I suppose. I'll get it into master in the next week or 2.
