### ISSUE TITLE
Contour ingress

### ISSUE THREAD

**Issue by tannevaled** [travisghansen/external-auth-server#112]
Hi, do you have any usage sample with the contour ingress controller?

**Comment by travisghansen** [comment]
Welcome! I was thinking contour never implemented the feature but just found this: https://projectcontour.io/guides/external-authorization/

so somewhere along the way it was implemented. Apparently they only allow the grpc and not both grpc and http which seems really odd. If you’d like to confirm that I’m happy to help make it work if any modifications are required (including building a grpc endpoint if indeed the http style is not possible).

**Comment by tannevaled** [comment]
Thanks for your quick reply. like you i think only grpc is available.

**Comment by travisghansen** [comment]
That's quite silly as the underlying envoy feature supports both, but I'm guessing adding a grpc endpoint to the service won't be crazy. Are you on the k8s slack or something where you could possibly collaborate and do some testing? I don't use envoy nor contour so a little help would probably go a long way :)

**Comment by tannevaled** [comment]
Yes you can find me on the k8s slack. I will be happy to help.

**Comment by travisghansen** [comment]
Support for this has landed in `next`. https://github.com/travisghansen/external-auth-server/commit/2d1d5cb8b2179b7cb816c5daabca402d94331474

The chart needs to be updated still to support the new port etc.

**Comment by travisghansen** [comment]
Officially released in `v0.11.0`. Support is available in the chart and the app.
