### ISSUE TITLE
Userinfo and Oauth2 flow

### ISSUE THREAD

**Issue by nonefaken** [travisghansen/external-auth-server#120]
Hello,

is "userinfo" functionality available in Oauth2 plugin?

I know the difference of use cases for oauth2 flows and getting openid flow, but wonder if it is possible, because you can include openid scope in Oauth2 flow/plugin:
```
scopes: ["user offline_access email profile openid"]
```
Also oauth2 plugin example contain userinfo configuration for github: https://github.com/travisghansen/external-auth-server/blob/e4646e151ca9062e0ace68b748fcd8d7c9c7471c/PLUGINS.md#oauth2

Thank you!

**Comment by travisghansen** [comment]
Userinfo is part of the oidc spec and so is natively supported there. With oauth2 it’s implemented on a provider by provider basis with currently only support for github. Others could be added to the code base however.

**Comment by nonefaken** [comment]
Clear. Thank you!
