### ISSUE TITLE
Logging in JSON format

### ISSUE THREAD

**Issue by nonefaken** [travisghansen/external-auth-server#123]
Hello,

is there an easy way to configure EAS output all logging information in JSON format?

By default the logs are not in JSON format and i have to chain it though Fluent-bit instance through regex parser, ie. `Regex        ^(?<eas_log_header>[^\{]*) (?<eas_json_log>[^*]*)$`.

This is not critical, but not very convenient, especially in kubernetes, then often platform by default only supports logs to stdout in JSON format, else it is like constant "playing with drums".

Thank you!

**Comment by travisghansen** [comment]
Are you running in k8s? It does json by default there.

**Comment by travisghansen** [comment]
https://github.com/travisghansen/external-auth-server/blob/master/src/logger.js

Basically it looks for `NODE_ENV=production`

**Comment by nonefaken** [comment]
so if i run on docker-compose and pass `NODE_ENV=production` it will be same effect?

**Comment by nonefaken** [comment]
It worked :) Thank you!

```
docker logs eas -f
{"service":"external-auth-server","level":"info","message":"revoked JTIs: []"}
{"service":"external-auth-server","level":"info","message":"starting server on port 8080"}
```
