### ISSUE TITLE
waitpid() returned a pid (2329550) we can't find in our scripts execution queue!

### ISSUE THREAD

**Issue by kettenbach-it** [travisghansen/external-auth-server#124]
Hi Travis,

I get the above message from time to time in my log.
What does it mean?
Does this message indicate a problem or should I ignore it?

Greetings
Volker

**Comment by travisghansen** [comment]
Hmm good question. I don’t recall seeing that but I don’t watch the logs really really closely. Are you using the exec feature at all writing custom js in the plugins?

**Comment by kettenbach-it** [comment]
> Are you using the exec feature at all writing custom js in the plugins?

Not that I know of

**Comment by travisghansen** [comment]
I think you can safely ignore it then. If you discover bad outcomes as a result please let me know however.

**Comment by kettenbach-it** [comment]
Okay! Thanks for your help!
