### ISSUE TITLE
ip whitelist + forwardauth

### ISSUE THREAD

**Issue by solipsist01** [travisghansen/external-auth-server#130]
Hello,

I have running eas + traefik 2.0 with forwardauth and keycloak.
Unfortunately, Traefik doesn't support OR chained middlewares.
https://github.com/traefik/traefik/issues/6007

Would it be possible to do this within EAS ?

i'd like to combine ip whitelist and forward auth.

if ip is in ipwhitelist, then no keycloak. you are authenticated and get the website presented
else, you are forwarded to keycloak, where you have to authenticate.

Would it be complicated to get this running?

**Comment by travisghansen** [comment]
Just put a `request_js` plugin in the list of plugins before the oidc plugin.

Something like this should do the trick. This of course assume `x-forwarded-for` is being properly set etc.

```
"snippet": "if (['ip1', 'ip2', ...].includes(req.headers['x-forwarded-for'])) res.statusCode = 200;",
```

I may have something not quite properly escaped there, but you get the idea.

https://github.com/travisghansen/external-auth-server/blob/master/PLUGINS.md#request_js

**Comment by travisghansen** [comment]
OK, busy week so sorry for the delay. This snippet works for me locally:

```
"snippet": "console.log(parentReqInfo); console.log(req.headers); if (['::1', '8.8.4.4'].includes(req.headers['x-forwarded-for'].split(',')[0].trim())) res.statusCode = 200; console.log(res);",
```

Replace the list of IPs as appropriate for your use-case obviously (`::1` was the operative value for me locally).

**Comment by solipsist01** [comment]
Im testing this first thing tomorrow!. Thanks for this :)

**Comment by solipsist01** [comment]
Hi Travis,

I have changed to cf-connecting-ip and then it works, so i'm all happy :)

Could it be that EAS doesn't handle x-forwarded-for as an array internally ?
The logging shows the headers, and it only has the cloudflare IP.

I have a headers container running which shows my headers, and that one does infact show multiple ip's

This is my console output of EAS.

```
info: starting verify for plugin: request_js
{
  uri: 'https://headers.redacted.nl/',
  parsedUri: {
    scheme: 'https',
    userinfo: undefined,
    host: 'headers.redacted.nl',
    port: undefined,
    path: '/',
    query: undefined,
    fragment: undefined,
    reference: 'absolute'
  },
  parsedQuery: {},
  method: 'GET'
}
{
  host: 'forwardauth:8080',
  'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/201001                                                                                                                                                             01 Firefox/93.0',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,imag                                                                                                                                                             e/webp,*/*;q=0.8',
  'accept-encoding': 'gzip',
  'accept-language': 'en-US,en;q=0.5',
  'cdn-loop': 'cloudflare',
  'cf-connecting-ip': '8.8.4.4',
  'cf-ipcountry': 'NL',
  'cf-ray': '6a7b447d9b694248-AMS',
  'cf-visitor': '{"scheme":"https"}',
  dnt: '1',
  'sec-fetch-dest': 'document',
  'sec-fetch-mode': 'navigate',
  'sec-fetch-site': 'none',
  'sec-fetch-user': '?1',
  'upgrade-insecure-requests': '1',
  'x-forwarded-for': '141.101.105.34',
  'x-forwarded-host': 'headers.redacted.nl',
  'x-forwarded-method': 'GET',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https',
  'x-forwarded-server': 'traefik',
  'x-forwarded-uri': '/',
  'x-real-ip': '141.101.105.34'
}
PluginVerifyResponse {
  statusCode: 500,
  statusMessage: '',
  body: '',
  cookies: [],
  clearCookies: [],
  headers: {},
  authenticationData: {},
  plugin: RequestJsPlugin {
    server: ExternalAuthServer { WebServer: [EventEmitter] },
    config: {
      type: 'request_js',
      snippet: "console.log(parentReqInfo); console.log(req.headers); if (['8.8.4.4', '8.8.4.4'].includes(req.headers['x-forwarded-for'].split(',')[0]                                                                                                                                                             .trim())) res.statusCode = 200; console.log(res);",
      pcb: {}
    }
  }
}

```

**Comment by travisghansen** [comment]
The satus code being 500 isn’t necessarily a problem of that’s what you’re asking about.

The `split` turns the value into an array, but yes if this is ‘behind’ cf then you’ll want to adjust as appropriate. In the example output above which ip is the client ip and which ip is the cf ip?

**Comment by solipsist01** [comment]
8.8.4.4 is my real wan ip
141.101.105.34 is the Cloudflare IP

My headers page shows the following:

```
X-Forwarded-For: 8.8.4.4, 141.101.77.227
X-Forwarded-Host: headers.redacted.nl
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Server: traefik
```

While EAS logging shows:

```
  'x-forwarded-for': '141.101.105.34',
  'x-forwarded-host': 'headers.redacted.nl',
  'x-forwarded-method': 'GET',
  'x-forwarded-port': '443',
```


Wouldn't this mean it only splits one ip ? because there is only one ip in the variables?

**Comment by travisghansen** [comment]
That seems odd that the header doesn’t have the wan ip as eas sees it. Can you send the middleware definition for me to review? And also the entry point if available?

**Comment by solipsist01** [comment]
```
labels:
      - "traefik.http.middlewares.keycloak-and-whitelist-auth.forwardauth.address=http://forwardauth:8080/verify?config_token=randomjibberishhashoutputfromjsfile"
      - "traefik.http.middlewares.keycloak-and-whitelist-auth.forwardauth.authResponseHeaders=X-Userinfo, X-Id-Token, X-Access-Token"

    command:
      - --entrypoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.insecure
      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.forwardedHeaders.insecure
```

**Comment by travisghansen** [comment]
What behavior do you see when you enable this: https://doc.traefik.io/traefik/middlewares/http/forwardauth/#trustforwardheader

**Comment by solipsist01** [comment]
You sir, are brilliant. That was the solution.

I never considered that for an forwardauth flow, headers would be handled diffrent.

**Comment by travisghansen** [comment]
It’s especially important for forward auth to ensure headers can be trusted :) In your case I would try to set those manually using curl or something to ensure they’re being cleansed properly end-to-end so someone can’t effectively spoof their ip (and subsequently bypass auth).

**Comment by solipsist01** [comment]
After some research, i cannot trust this header indeed. Im gonna use cf-connecting-ip and make sure traffic only comes from cloudflare ips, as cloudflare always overwrites that header. Thank you!
