### ISSUE TITLE
JWT Plugin and custom_service_headers

### ISSUE THREAD

**Issue by peadarDoyle** [travisghansen/external-auth-server#154]
So I'm using Keycloak, Traefik 2 and external-auth-server for OIDC flows (using the OIDC plugin) and it works great. Using `custom_service_headers` I forward the access token to my API as plain JSON rather than as a JWT.

I'm now making my API machine-to-machine ready and I'm adding the JWT plugin where the client gets the access token via Keycloak first and then sends it as a Bearer token. I'm using the following config token with the `custom_service_headers` just like I do in the OIDC plugin:

```
{
  "eas": {
    "plugins": [
      {
        "type": "jwt",
        "header_name": "Authorization",
        "scheme": "Bearer",
        "config": {
          "secret": ""
        },
        "oidc": {
          "enabled": true,
          "issuer": {
            "discover_url": "https://example.com/auth/realms/foo/.well-known/openid-configuration"
          }
        },
        "client": {
          "client_id": "my-client",
          "client_secret": "a51..."
        }
      }
    ],
    "custom_service_headers": {
      "X-Token": {
        "source": "access_token",
        "query_engine": "jp",
        "query": "$",
        "query_opts": {
          "single_value": true
        }
      }
    }
  }
}
```

The auth flow works great but I get the following errors in the logs when it attempts to set my custom `X-Token`:
```
failed setting header: X-Token error: Error: invalid data source: access_token
    at HeaderInjector.query (/home/eas/app/src/header/index.js:76:17)
    at HeaderInjector.injectHeaders (/home/eas/app/src/header/index.js:21:30)
    at /home/eas/app/src/server.js:499:33
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async verifyHandler (/home/eas/app/src/server.js:93:5)
```

I'm a little bamboozled by the fact that it can't access the `access_token` when I also see in the logs that the 'X-Access-Token' is available. As it stands I've made my API handle both the `Authroization: Beaer eyj...` and the `X-Token: {...access toke in plain json...}` headers.

Any help understanding why the `access_token` isn't a valid data source and/or what I can do to get the behavior I want (i.e. both flows resulting in the `X-Token` forwarded to my API) would be appreciated. The fact that the OIDC plugin is stateful is something I've been wondering if it has impact here.

Technically things work at the moment - it just feels a bit messy having to parse the access token from a JWT in my API.

**Comment by travisghansen** [comment]
Welcome! In `oidc` we deal with a set of tokens. In `jwt` there’s no notion of multiple tokens…it’s just ‘the’ token. So while in your case using an oidc provider to get the token it is considered an access token in other cases it may not have anything to do with `oidc` semantics.

In short long ago I made a decision in the case of `jwt` to refer to ‘the’ token as `id_token` as that to me is a better representation of what it is in the purest sense of the use-case https://github.com/travisghansen/external-auth-server/blob/master/src/plugin/jwt/index.js#L313

However I’m pragmatic and wouldn’t be against setting both properties to the same value if its of use as I can see how that could be beneficial in some scenarios.

**Comment by peadarDoyle** [comment]
> Welcome!

A returning customer :smile:   
But thanks all the same.

Your reasoning for using `id_token` makes sense, I guess more digging through the source would have proven fruitful, I tried other sources (though more to verify I could source something in the jwt flow) but hadn't tried the `id_token`. Since the `custom_service_headers` can be set per plugin it should be rather trivial to have one per plugin even if they are very similar.

Currently I have a config token per client/tenant combination. And I don't have tenants that use both oidc and jwt yet. But I do expect I will at some point and something like the `pcb` will probably be useful then. Or I could even treat the same API as two different clients depending on whether it is being used programmatically or as a backend-for-frontend.

I just tested the config token using the `id_token` and I have things working as originally envisaged.

Thanks for the help and the quick follow up. Much appreciated.

**Comment by travisghansen** [comment]
Yeah, in my case I have a single config where everything is technically backed by ldap but I can use jwt, basic, or oidc. I just check the auth header for `Bearer` and use `jwt` in that scenario, otherwise `Basic` and use `ldap` in that scenario, otherwise fallback to `oidc`. Covers all my bases with 1 token :D
