### ISSUE TITLE
eas fails to handle x-userinfo with non-ascii characters

### ISSUE THREAD

**Issue by kettenbach-it** [travisghansen/external-auth-server#161]
Hi Travis,

having a user in our OIDC IAM with non-ascii chars in the first- and lastname (not in the username)

<img width="539" alt="image" src="https://user-images.githubusercontent.com/7711872/198112042-f449e60a-3f40-4862-b1f5-2297240e03e7.png">

leads to this:

```
eas-hfpsk external-auth-server 2022-10-26T20:45:18.185532248+02:00 
{"code":"ERR_INVALID_CHAR","level":"error","message":"Invalid character in header content [\"X-Userinfo\"]",
"service":"external-auth-server","stack":"TypeError [ERR_INVALID_CHAR]: Invalid character in header content 
[\"X-Userinfo\"]\n    at ServerResponse.setHeader (node:_http_outgoing:606:3)\n    at ServerResponse.header 
(/home/eas/app/node_modules/express/lib/response.js:794:10)\n    at Function.setResponse 
(/home/eas/app/src/index.js:19:11)\n    at /home/eas/app/src/server.js:533:28\n    at runMicrotasks (<anonymous>)\n    
at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async verifyHandler 
(/home/eas/app/src/server.js:93:12)","timestamp":"2022-10-26T18:45:18.184Z"}
```

It's reproducible with Keycloak as IAM as well.

**Comment by kettenbach-it** [comment]
Hi Travis,
we found out, that the "roofs" in slovenian are not in UTF-8 (but UTF-16 or UTF-8-si or so).
So eas work's as designed, right?
What do you think?

**Comment by travisghansen** [comment]
Per the spec http headers only allow ascii :( The value likely needs to be url or bas64 encoded I guess.

**Comment by travisghansen** [comment]
Is it passing data in headers? If so it has to be encoding it with one of the above options or just converting the non-ascii chars to ascii..

**Comment by kettenbach-it** [comment]
That's a good question!
Isn't the X-user info transferred directly between RP and OP? Then I wouldn't be able to see it anyway.
I also played around a bit today: I added one of these special characters to the name of my own account. In the Admin-Console (no SPA) it was displayed correctly. In SPAs like GMail or the calendar, however, my name is displayed as it was *before* the change - even though the change was made many hours ago..... Strange... Maybe Google avoids to transfer such a name into the heander and therefore leaves it with the old name!?
I would have to create a new account. But I haven't had the time yet.

I'll close this issue, since it's not a bug anyway.

**Comment by travisghansen** [comment]
Let’s leave it open for a little bit as it’s something I should be handling in some shape or form. I’ll look into ideas for options to encode the data properly.

I won’t be able to look into most of this stuff for another couple weeks though :(

**Comment by travisghansen** [comment]
I have added a new feature (https://github.com/travisghansen/external-auth-server/commit/b26a1a2ec62e0163d3a3cc24cbfd5bf4bdd0151b) to allow encoding headers, just add something like the following:

```
    custom_service_headers:
      X-Userinfo:
        source: userinfo
        encoding: base64
```

**Comment by travisghansen** [comment]
This has been released in `v0.13.0`.

**Comment by kettenbach-it** [comment]
Hi Travis,

I came across this topic again. Again because of a name from Eastern Europe (I created the account myself but forgot about the limitation).
Since we will soon be setting up a public, automatic signup facility, I need to look into how we can make the process more robust here, so that names with special characters don't generate 500s in eas and break the UX.

You say in a previous comment that `X-Userinfo` by definition may only contain ASCII characters.
Apparently this is not the case with Google IAM, otherwise the Eastern European names would be displayed encoded and eas would not terminate with a 500. Correct or am I inferring wrong here?

If this is the case, I might need to sanitize the users name before creating the account in IAM.

**Comment by kettenbach-it** [comment]
@travisghansen I'll mention you because you might overlook my above comment because the ticket is already closed

**Comment by travisghansen** [comment]
Hey! Yeah and I saw it and was doing some research. It appears that my previous comment is still valid. I would be interested to see what the behavior is that google is doing. I think besides base64 encoded we should add URL encoding the value.  Can you send over what the userinfo data looks like when it has those chars and is url encoded?

**Comment by kettenbach-it** [comment]
Hi! I was already thinking to do that. But I assume I have to write some code to do that, because
- I cannot use the "whoami" container als usual, since eas fails with a 500
- There seems to be no easy way to use the browser to get that userinfo

Do you have an idea how to quickly extract that userinfo?

**Comment by travisghansen** [comment]
It doesn’t need to be the exact info..just any string with those chars is fine.

If you enable debug logging it may log the userinfo response to the console though if that helps.

**Comment by kettenbach-it** [comment]
Hi Travis,

my Testaccount leads to the following x-userinfo (extracted from the eas' debug log):

```
X-Userinfo: {
"sub":"101694514751337468681",
"name":"Sašo Kanturič",
"given_name":"Sašo",
"family_name":"Kanturič",
"picture":"https://lh3.googleusercontent.com/.......",
"email":"saso@xxxxxxxx.de",
"email_verified":true,
"locale":"de",
"hd":"xxxxxx.de"
}
```

These little upside-down roofs on the chars are typical for several eastern european languages.
The are the cause of the 500.

Fore some reason, the german "Umlaute": ä, ü, ö do not cause problems.
Here's x-userinfo of an account only having Umlaute:

```
X-Userinfo: {
"sub":"101694514751337468681",
"name":"Sasü Kanturiä",
"given_name":"Sasü",
"family_name":"Kanturiä",
"picture":"https://lh3.googleusercontent.com/....",
"email":"saso@xxxxxx.de",
"email_verified":true,
"locale":"de",
"hd":"xxxxxx.de"
}
```

This userinfo doesn't produce a 500 in eas

**Comment by travisghansen** [comment]
```
 ~  echo '{
"sub":"101694514751337468681",
"name":"Sasü Kanturiä",
"given_name":"Sasü",
"family_name":"Kanturiä",
"picture":"https://lh3.googleusercontent.com/....",
"email":"saso@xxxxxx.de",
"email_verified":true,
"locale":"de",
"hd":"xxxxxx.de"
}' | jq -c .
{"sub":"101694514751337468681","name":"Sasü Kanturiä","given_name":"Sasü","family_name":"Kanturiä","picture":"https://lh3.googleusercontent.com/....","email":"saso@xxxxxx.de","email_verified":true,"locale":"de","hd":"xxxxxx.de"}
 ~  node
Welcome to Node.js v18.18.0.
Type ".help" for more information.
> let foo = '{"sub":"101694514751337468681","name":"Sasü Kanturiä","given_name":"Sasü","family_name":"Kanturiä","picture":"https://lh3.googleusercontent.com/....","email":"saso@xxxxxx.de","email_verified":true,"locale":"de","hd":"xxxxxx.de"}'
undefined
> encodeURI(foo)
'%7B%22sub%22:%22101694514751337468681%22,%22name%22:%22Sas%C3%BC%20Kanturi%C3%A4%22,%22given_name%22:%22Sas%C3%BC%22,%22family_name%22:%22Kanturi%C3%A4%22,%22picture%22:%22https://lh3.googleusercontent.com/....%22,%22email%22:%22saso@xxxxxx.de%22,%22email_verified%22:true,%22locale%22:%22de%22,%22hd%22:%22xxxxxx.de%22%7D'
```

**Comment by kettenbach-it** [comment]
What do you mean by that?
That the userinfo should be url-encoded?
I have no influence on that, since this is done by the Google IdP.

**Comment by kettenbach-it** [comment]
And: you took the one with the Umlaute which works.
Try the on with the little roofs on the letters.

**Comment by travisghansen** [comment]
Can you send a sample of the google stuff?

```
'%7B%22sub%22:%22101694514751337468681%22,%22name%22:%22Sa%C5%A1o%20Kanturi%C4%8D%22,%22given_name%22:%22Sa%C5%A1o%22,%22family_name%22:%22Kanturi%C4%8D%22,%22picture%22:%22https://lh3.googleusercontent.com/.......%22,%22email%22:%22saso@xxxxxxxx.de%22,%22email_verified%22:true,%22locale%22:%22de%22,%22hd%22:%22xxxxxx.de%22%7D'
```

I'm suggesting that we can set the value to be URL encoded to adhere to the ascii requirement.

**Comment by kettenbach-it** [comment]
Look at my comment above.
Both userinfos are from Google.
The first contains the deadly characters.
The second is okay.

**Comment by travisghansen** [comment]
Sure, I understood you were suggesting that google has some product which is passing those values via a header (some other product not related to `eas`). Did I misunderstand that?

**Comment by kettenbach-it** [comment]
The bottom line is that I just want to know how to avoid this error 500 (except by sanitizing firstname and lastname on user creation)!

The information that is available is:
- It happens with special Eastern European characters, not with German umlauts (which are also not ASCII characters)
- It happens with the X-Userinfo from Google Identity Provider
- It also happens the X-Userinfo from Keycloak

You asked me the question if Google transmits this information via a header: In `eas` the log it says: `Invalid character in header content ["X-Userinfo"]`, so I guess you are right and `eas` get's this via a header.
In any case, Google/Keycloak sends something to `eas` which generates the 500. 

The question now is: should `eas` not actually be able to process this userinfo!? It does not seem to be unusual for two quite common identity providers to transmit these characters.

**Comment by travisghansen** [comment]
Yeah, I misunderstood what you were suggesting. In any case, the only solution is to encode the data in some way..you can either base64 it or we can add URL encoding add as an option as well. UTF being sent in a header is out of spec.

**Comment by kettenbach-it** [comment]
Okay, I might have missunderstood you as well.

Does `eas` raise the 500 on _setting_  the header in a reply it sends or on _receiving_ a header from Google?

**Comment by kettenbach-it** [comment]
I slept on this and I think I now understand what is happening:

i thought all the time `eas` throws the 500 when it _receives_ the userinfo from google.
So I didn`t understand why encoding the headers with base64 should be a solution.

But now I understand that the problem happens when _creating_ the HTTP request that `eas` _sends_ to my application.
So base64 encoding _is_ a solution.

From the two possible solutions base64- and url-encoding, I think url-encoding would actually be better. The reason for this is that headers, which per se contain only ASCII characters, are not changed by the encoding and applications, which do not support decoding of the header, then still work and in the case of pure ASCII headers also display everything correctly. In case of url encoded headers there would be jibberish in the corresponding field, but there would be no decoding error.

So if you want to implement url encoding: very welcome!

But I will implement base64 tomorrow, because I want to finish our public signup next week and don't want to wait for the next release of `eas`. If you implement url encoding, I will switch to that later.

**Comment by travisghansen** [comment]
Great! Sorry the wires got crossed there on communication :) I can make a release quickly if it helps…just merged a small PR yesterday that has also been tested at this point so need to get that out as well.

**Comment by kettenbach-it** [comment]
If you could do a quick release, that would be awesome!

**Comment by travisghansen** [comment]
It’s in `next` if you could test. Waiting for 1 other thing to be tested as well before snapping a release.

**Comment by kettenbach-it** [comment]
Is it like this
```
    custom_service_headers:
      X-Userinfo:
        source: userinfo
        encoding: url
```
?

**Comment by travisghansen** [comment]
Sorry, it's `uri` not `url`.

**Comment by kettenbach-it** [comment]
Thx! I'll will implement both in my software: base64 and uri and then I can test both of your options. I'll get back to you asap

**Comment by kettenbach-it** [comment]
Hi Travis,

I can report a successful implementation:
I have implemented both uri- and base64-encoding in our software and successfully tested both variants with the next branch.
Thanks a lot for your help!

**Comment by kettenbach-it** [comment]
I'd close this issue now since it's resolved and runs in production for a couple of weeks now
