### ISSUE TITLE
GitHub Oauth Permission Write?

### ISSUE THREAD

**Issue by autarchprinceps** [travisghansen/external-auth-server#166]
Using EAS with GitHub Oauth requests "Update all user data". Shouldn't read access at the most be enough?

**Comment by travisghansen** [comment]
That’s generally setup when you create the client right? I don’t think `eas` really cares what the associated permissions are. If you are leveraging the github `userinfo` bit then the scopes should include enough permissions to invoke the enabled endpoints. They are all GET requests though.

https://github.com/travisghansen/external-auth-server/blob/master/src/plugin/oauth/index.js#L2371

**Comment by travisghansen** [comment]
Also what did you put in the `scopes` parameter of the plugin config?

**Comment by autarchprinceps** [comment]
We used the contrib/generate-config-helm-traefik-github.js script.
As far as I see the scopes there is: scopes: ["user"]
userinfo: {
            provider: "github",
            config: {
              fetch_teams: true,
              fetch_organizations: true,
              fetch_emails: true
            }
          }
and then a read only assertion whether the github team ID is one of those we provided.

**Comment by travisghansen** [comment]
Ah, so that’s the issue. Scopes are available here: https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps

- `read:user`
- `user:email`
- `read:org`

I would start with those 3 and see if everything works.

**Comment by travisghansen** [comment]
Great!

**Comment by autarchprinceps** [comment]
Yeah, that works fine. I can still access Ingress with those scopes, and I get read only displayed now.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/239063/213461364-c6d28243-8a9b-4d88-9ae5-b75e3dd22970.png">
https://github.com/travisghansen/external-auth-server/pull/167

**Comment by travisghansen** [comment]
Can you share the assertions you have on the userinfo?

**Comment by autarchprinceps** [comment]
That part didn't need to change. We primarily assert against team membership, which can include multiple teams, incl. different organisations, and MFA.
```js
{
assertions: {
    /**
     * assert the token(s) has not expired
     */
    exp: true,
    userinfo: [
      {
        query_engine: "jp",
        query: "$.teams[*].id",
        rule: {
          method: "contains-any",
          value: github_team_ids
          //negate: true,
          //case_insensitive: true
        }
      },
      {
        query_engine: "jp",
        query: "$.two_factor_authentication",
        rule: {
            method: "eq",
            value: true,
            //negate: true,
            //case_insensitive: true
        }
      }
    ]
  }
}
```

**Comment by autarchprinceps** [comment]
We completely use the public script version, and fill it with a .env with the parameters mentioned on the top of the script for different environments. Aside from those GitHub secrets obviously, there is nothing we are keeping hidden.

**Comment by runningman84** [comment]
@travisghansen we have seen this behavior recently:
![eas_auth](https://github.com/travisghansen/external-auth-server/assets/1699128/000a0f87-0ad3-437c-a0e6-e583262a2fa9)
Why is it still requesting "update all user data"?
The configuration was created using this script:
https://github.com/travisghansen/external-auth-server/blob/master/contrib/generate-config-helm-traefik-github.js

**Comment by travisghansen** [comment]
I’m not super familiar with all the github scopes etc unfortunately. Are there some default scopes set for the client id/secret that may be causing something like that?
