### ISSUE TITLE
Semi colons are replaced by ampersands after logout

### ISSUE THREAD

**Issue by djbulsink** [travisghansen/external-auth-server#171]
Hi Travis,

When we use dat semi colon in the redirect_uri of a logout request. It the semi colon will be replaced by an ampersand. 

example:

I want te redirect to `https://gateway-test.ahp-test.geodan.it/privecho?a=foo;bar` after i'm logged out.

So i call this logout url:
`https://example.com/?__eas_oauth_handler__=logout&redirect_uri=https%3A%2F%2Fexample.com%3Fa%3Dfoo%3Bbar`

The logout works correct only afterwards I'm redirected to: `https://example.com/privecho?a=foo&bar`

Is this something that can be fixed?

regards, DJ

**Comment by travisghansen** [comment]
You want that to be part of the value for `a` query param?

**Comment by djbulsink** [comment]
yes, i would expect that the value of `a` would be `foo;bar` . But it's changed to `a=foo&bar`.

**Comment by djbulsink** [comment]
I think it's related to this discussion: https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator

**Comment by travisghansen** [comment]
Perhaps. What proxy/ingress are you using? I’ll do some testing to see where the breakdown is.

Assuming the proxy is passing down sanely this does the parsing: https://www.npmjs.com/package/query-string

**Comment by djbulsink** [comment]
Sorry, I'm just noticed that it's not an issue with the logout redirect, but it's going wrong with the oidc login. In my example the url `https://example.com/privecho?a=foo;bar` is protected by EAS.

So, if you would go to `https://example.com/privecho?a=foo;bar`. Which is protected by EAS. The user will be redirect after the oidc login callback to `https://example.com/privecho?a=foo&bar`

**Comment by travisghansen** [comment]
Logout works correctly? oidc redirects are not working correctly?

**Comment by djbulsink** [comment]
Yes, there is no problem with the logout. But the issue is appears with oidc redirect after login callback.

**Comment by travisghansen** [comment]
Wow.
