### ISSUE TITLE
Question about cookie lifetime?

### ISSUE THREAD

**Issue by mstenz** [travisghansen/external-auth-server#173]
we have an application behind traefik and eas. it uses ws protocol, after some time the application stops working as it would require reload. 
The time it times out is something probably between 10 minutes and 30 minutes, but i am not sure exactly. Is there any way to define how long the session cookie is set so this doesnt happen? 

Or is this something traefik is doing?

**Comment by travisghansen** [comment]
You can control when the cookie expires yes, but if the socket is closing that seems unrelated to `eas`.

**Comment by mstenz** [comment]
Thank you. After some more little searching I think this is because of the default idleTimeout Intervall of Traefik of 180s. 
I can configure the application ping intervall lower, I think this should hopefully fix the problem. Thank you.
