### ISSUE TITLE
custom_service_headers not being injected 

### ISSUE THREAD

**Issue by pbichinepally-sunpower** [travisghansen/external-auth-server#174]
![image](https://github.com/travisghansen/external-auth-server/assets/70723765/a29ee4e6-6c29-4c77-95ab-ee91717a63b8)

This is the structure of the EAS I am using, and I am integrating this with Traefik Middleware and this is the response I am getting in the auth-server logs:
{"level":"debug","message":"plugin response {\"statusCode\":200,\"statusMessage\":\"\",\"body\":\"\",\"cookies\":[],\"clearCookies\":[],\"headers\":{\"X-Access-Token\":\"###"},\"authenticationData\":{\"id_token\":\"###\"},\"plugin\":{\"server\":{},\"config\":{\"type\":\"jwt\",\"realm\":\"my realm\",\"header_name\":\"Authorization\",\"scheme\":\"Bearer\",\"config\":{\"secret\":\"####/v1/keys\",\"options\":{\"aud\":\"/v1\"}},\"oidc\":{\"enabled\":true,\"issuer\":{\"issuer\":\"####\",\"authorization_endpoint\":\"####/v1/authorize\",\"token_endpoint\":\"####/v1/token\",\"userinfo_endpoint\":\"####/userinfo\",\"jwks_uri\":\"####/v1/keys\"},\"features\":{}},\"features\":{\"introspect_access_token\":true,\"fetch_userinfo\":true},\"assertions\":{\"id_token\":[{\"query_engine\":\"jsonata\",\"query\":\"aud\",\"rule\":{\"method\":\"eq\",\"value\":\"###/v1\"}}]},\"custom_service_headers\":{\"X-Injected-Scopes\":{\"source\":\"id_token\",\"query_engine\":\"jsonata\",\"query\":\"\",\"encoding\":\"plain\"}},\"pcb\":{}}}}","service":"external-auth-server","timestamp":"2023-05-17T20:35:28.990Z"}

I don't see the custom_service_headers in the plugin response
Please suggest what I am missing

**Comment by pbichinepally-sunpower** [comment]
Yes, I was able to successfully custom_service_headers, changed the `features` to place it inside the `oidc`. 
I was able to successfully service headers by using `filtered_service_headers` block in the `features` block. 

Is there a way to filter non-service headers like "x-powered-by","authorization","Content-Type"

For example:  
filtered_service_headers: ["x-access-token","x-powered-by","authorization","Content-Type"] -- This block filters "x-access-token" but not the other non-service headers.

Is there a way to achieve this ?

please suggest

**Comment by travisghansen** [comment]
Usually the proxy handles this aspect. What are you using for a proxy?

**Comment by pbichinepally-sunpower** [comment]
I am using Traefik.
Tried to add this :
```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: jwt-pricing-int-remove-headers
spec:
  headers:
    customResponseHeaders:
      X-Powered-By: ""
``` 
any suggestions on this ?

**Comment by travisghansen** [comment]
https://doc.traefik.io/traefik/v2.0/middlewares/forwardauth/#authresponseheaders

It’s in the forward auth middleware configuration. Remove the middleware above from the ingress altogether.

**Comment by travisghansen** [comment]
Get it working as needed?

**Comment by pbichinepally-sunpower** [comment]
Yes, it is working as expected, Thanks.
