### ISSUE TITLE
Architectural question: does Traefik receive the token issued by eas?

### ISSUE THREAD

**Issue by kettenbach-it** [travisghansen/external-auth-server#183]
Hi Travis,

I am currently working with a large client to build eas into an architecture consisting of Keycloak, Traefik and an application "behind" Traefik in the k8s cluster.
That in itself is not unusual - but due to the fact that the application has an exceptional architecture, we have special requirements:
- We cannot pass the token to the app using HTTP headers
- Instead, the token needs to be send over a rest API to a another component living in the cluster
- The token could either be sent by eas itself - this is technically possible but we'd like to evaluate the next option:
- Or - and this is the question - a traefik plugin could handle that job.
Now my question is: does traefik receive the token at all or is the token passed by eas to the application "behind" it?

Best regards
Volker

**Comment by travisghansen** [comment]
`eas` generally has no knowledge of the app 'behind' the proxy. So (if configured) the headers are sent to traefik and traefik then passes those headers down to the app.

Given the above, it's perfectly viable to create a traefik plugin that 'intercepts' the headers and pushes them to a separate desired location. You just need to ensure that plugin is run *after* the external-auth step in traefik's internals.

**Comment by kettenbach-it** [comment]
Hi Travis, great! Thanks for the quick answer! Best regards! Volker
