### ISSUE TITLE
human readable reusable auth url

### ISSUE THREAD

**Issue by runningman84** [travisghansen/external-auth-server#21]
As discussed offline we would really like to use server side tokens and in multiple clusters and applications. Therefore each cluster has unique secrets used by the external auth server. Right now each protected application in each cluster has a completely different auth url. This makes it quite difficult to manage on a large scale.

I would like to have a human readable reusable auth url (where only the base url/domain is different). 

Right now the auth url looks like this:
```
https://eas.${base_domain}/verify?config_token=${config_token_alias_encrypted_uri}
```

I would like to use the auth url liks this:
```
https://eas.${base_domain}/verify?config_token_id=team_github_operators&config_token_store_id=primary
https://eas.${base_domain}/verify?config_token_id=team_github_customer
https://eas.${base_domain}/verify?config_token_id=team_github_developers
```
The config_token_store_id should be optional, primary should be the default value there.

**Comment by travisghansen** [comment]
This has been committed in `v0.5.0` and is included in `latest` now. `config_token_store_id` however is required and makes no assumptions about it's value.

Thanks for the feedback!
