### ISSUE TITLE
Run generate-config-token.js on runtime

### ISSUE THREAD

**Issue by iTaybb** [travisghansen/external-auth-server#28]
At the moment, it is required to generate a config token before actually using the app.
This token can be used with the app.
In docker environment, it's best practice to be able to provide everything on runtime in 1 step.

Maybe the config_token variable should be extracted from generate-config-token.js to a different file. And that file might be mounted with docker on runtime. The token will be calculated in the entrypoint, just before the app itself runs.

**Comment by travisghansen** [comment]
Thanks for the interest! I'm not sure I follow the thought process here. Unless using server-side tokens the service has no knowledge of tokens (only secrets to verify and decrypt) at launch time as everything is passed in on a per-service basis.

**Comment by travisghansen** [comment]
Do you have any remaining questions on this?
