### ISSUE TITLE
Feature request: support client credentials flow

### ISSUE THREAD

**Issue by mlushpenko** [travisghansen/external-auth-server#34]
I know I am keeping you busy :) here's one more use case: doing EAS-protected API testing or accessing it from code https://auth0.com/docs/flows/concepts/client-credentials. (auth0 is just an example provider)

For now, we are using JWT plugin for something like that, but users have to get access_token from somewhere first before they can call API behind the EAS, I think client credential flow is a more proper way to do it.

**Comment by travisghansen** [comment]
I may misunderstand, are you thinking eas should make a request to the auth server on behalf of the user to return the token? How do you envision it as part of the picture?

**Comment by mlushpenko** [comment]
@travisghansen sorry for confusing you, another ignorance on my side. Closing this one.

**Comment by travisghansen** [comment]
For others finding this, my understanding of the workflow here is that the `realm` property should be set appropriately and clients should be 'intelligent' to understand that if they need a new token they should expect a 403 and then request the token from the returned `realm` in the `www-authenticate` header.

**Comment by mlushpenko** [comment]
We are generally discussing how APIs should be authenticated and how it can work together with EAS. Before EAS, some APIs were partially open and devs could propagate their own credentials to login endpoint, get token and work with that for all other API calls. So, with EAS, as a first step, we will leave login endpoint open and after the token is retrieved, we will use JWT plugin for everything else. Until we come up with a better way to manage API authentication.

So, if you will be adding possibility to have some endpoints public to EAS, that would be great as we discussed on another issue.

**Comment by travisghansen** [comment]
Yes I will be shortly. That's part of why I was performance testing jq actually.
