### ISSUE TITLE
Using existing Redis on k8s

### ISSUE THREAD

**Issue by jeroenroodnat** [travisghansen/external-auth-server#37]
I am trying to setup a new EAS on k8s. On this cluster I already have redis up and running. When I run the helm install with: 

--set redis-ha.enabled=true \
--set redis-ha.auth=true \
--set redis-ha.redisPassword=[...]\
\
--set storeOpts.store=ioredis \
--set storeOpts.password=[...]\
--set storeOpts.name=mymaster \
--set storeOpts.sentinels[0].host=redis \
--set storeOpts.sentinels[0].port=26379 \
--set storeOpts.keyPrefix="eas:" \

Redis is installed as part of the Helm chart. How do I point EAS to my existing redis without installing Redis together with EAS?

**Comment by jeroenroodnat** [comment]
Correct, using an existing redis installation. Redis is already running and serving other applications. I want to let eas use same redis setup.

**Comment by travisghansen** [comment]
Ok yeah. I'll draft up some options and send them shortly. You'll want to pick a unique suffix for each eas install to be served by the same redis instance (or different db for each).

**Comment by travisghansen** [comment]
Is your existing redis install running with sentinel?

**Comment by jeroenroodnat** [comment]
Yes

**Comment by travisghansen** [comment]
OK, so disable eas from deploying it's own redis with:

```
--set redis-ha.enabled=false
```

Then configure eas to speak to your existing redis with:

```
--set storeOpts.store=ioredis \
--set storeOpts.password=<your password> \
--set storeOpts.name=<master name> \
--set storeOpts.sentinels[0].host=<host0> \
--set storeOpts.sentinels[0].port=26379 \
--set storeOpts.sentinels[1].host=<host1> \
--set storeOpts.sentinels[1].port=26379 \
--set storeOpts.sentinels[2].host=<host2> \
--set storeOpts.sentinels[2].port=26379 \
--set storeOpts.keyPrefix="eas:" \
```
I don't know where the existing install is in your cluster so you'll obviously need to adjust host names to something resolvable by your deploy/namespace etc. Also, it's the `storeOpts.keyPrefix` parameter that should be unique across `eas` installs should you have more than 1.

**Comment by jeroenroodnat** [comment]
great! thank you.

The first part "--set redis-ha.enabled=false" was the confusing part for me. I assumed it meant disabling redis integration completely

**Comment by travisghansen** [comment]
Yeah, that's a/the condition for the `redis-ha` subchart. I can see how that would be confusing. Let me know if you get it to successfully connect.

**Comment by jeroenroodnat** [comment]
got it working

**Comment by travisghansen** [comment]
Nice! Out of curiosity can you share what plugins you're using? I'm trying to get some insight into what features folks are using..

**Comment by jeroenroodnat** [comment]
k8s setup with traefik 1.7 and auth0. k8s multiple nodes with redis sentinel (for eas and other apps) and consul for traefik

**Comment by travisghansen** [comment]
So mostly `oidc` for `eas` plugins?

**Comment by jeroenroodnat** [comment]
yes
