### ISSUE TITLE
Helm repo

### ISSUE THREAD

**Issue by StianOvrevage** [travisghansen/external-auth-server#39]
First of thanks for creating this!

Would it be possible to publish the helm chart in a helm repo so that a regular `helm install` can be used to install without having to download and manage files locally?

I know it's a bit of work to get charts into the stable repo, but you can self-host a helm repo right here using GitHub pages actually. Here is a tutorial on how to do it: https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417

**Comment by travisghansen** [comment]
@StianOvrevage thanks for the interest! I do plan on upstreaming the chart to stable yes. I was holding off a little bit until '1.0' as I have a few breaking changes to the app planned :( My thought process has been if I put it on stable it'll get quite a bit more exposure that may be hurtful before the 1.0.

In any case, hosting with github pages direct on the project seems like a happy medium. I'm currently at kubecon actually so I'm pretty tied up the next couple days but I'll review early next week.

**Comment by tverhoeven** [comment]
+1 on getting a public helm chart somewhere. One less item for us to track ourselves in out git tree.

**Comment by travisghansen** [comment]
`helm repo add eas https://travisghansen.github.io/external-auth-server`
