### ISSUE TITLE
OAuth refresh tokens not being used

### ISSUE THREAD

**Issue by kevinoconnor7** [travisghansen/external-auth-server#44]
The title is bit overly broad but over the last few days I've been trying to track down a long-standing issue where clients need to login after about an hour or so. It's not clear to me if my setup is just misconfigured or if there's a real bug here, but I wanted to open a thread to investigate. At the very least I think the documentation about refresh tokens needs to better spell out how to configure things.

My current config is (minus some unrelated stuff):

```js
{
  /**
  * how to expire the cookie
  * true = cookies expire will expire with tokens
  * false = cookies will be 'session' cookies
  * num seconds = expire after given number of seconds
  */
  cookie_expiry: 60 * 60 * 24 * 30,

  /**
  * how frequently to refresh userinfo data
  * true = refresh with tokens (assuming they expire)
  * false = never refresh
  * num seconds = expire after given number of seconds
  */
  userinfo_expiry: false,

  /**
  * how long to keep a session (server side) around
  * true = expire with tokenSet (if applicable)
  * false = never expire
  * num seconds = expire after given number of seconds (enables sliding window)
  *
  * sessions become a floating window *if*
  * - tokens are being refreshed
  * or
  * - userinfo being refreshed
  * or
  * - session_expiry_refresh_window is a positive number
  */
  session_expiry: 60 * 60 * 24 * 30,

  /**
  * will re-use the same id (ie: same cookie) for a particular client if a session has expired
  */
  session_retain_id: true,

  /**
  * if the access token is expired and a refresh token is available, refresh
  */
  refresh_access_token: true,

  /**
  * which token (if any) to send back to the proxy as the Authorization Bearer value
  * note the proxy must allow the token to be passed to the backend if desired
  *
  * possible values are access_token, or refresh_token
  */
  authorization_token: "access_token",

  /**
  * fetch userinfo and include as X-Userinfo header to backing service
  * only helpful if your specific provider has been implemented
  */
  fetch_userinfo: true,
}
```

The reason `cookie_expiry` and `session_expiry` are set to the same value is due to #43, but I think you'd basically always want that anyway. It doesn't really max sense to have the cookie ever expire sooner than the session, at least if I understand correctly.

The reason the expiry is 30 days is because that's how long the refresh token I'm provided lasts. The `access_token` I'm provided is good for 60 minutes.

With all of this configured I'm still seeing users needing to login again after a couple of hours. I am using redis to persist session data so it should tolerate eas being restarted and what not.

My current theory is that refresh works _once_. So basically after an hour from the initial login the refresh token get used to get a new `access_token` but then someone isn't persisting properly and an hour after that login fails again. I haven't proven this is the case yet though.

**Comment by travisghansen** [comment]
This is oauth or oidc? Can you send over a sample of the `tokenSet` data?

**Comment by kevinoconnor7** [comment]
oidc... I'll get a `tokenSet` later tonight as I'll need to fire my debug instance. I'll also hack up the code a bit to force a refresh earlier so I can get the `tokenSet` before and after refresh.

**Comment by travisghansen** [comment]
OK, also to be clear, this only happens with mobile clients as mentioned on the other thread?

**Comment by kevinoconnor7** [comment]
Unclear -- it might just be coincidence that I notice it more on mobile since I tend to leave tabs open longer there and just generally use it more often.

**Comment by travisghansen** [comment]
Ok, in my case I only have issues in mobile. Also I don't think I'm impacted by your MR as I have the value set to `false` for my config.

I've always just assumed it was something different with how mobile browsers handle session cookies (ie: delete them due to space constraint concerns or the like). In any case, the next time it pops up for me I'll actually dig through the logs to see why it redirected me and start from there.

**Comment by kevinoconnor7** [comment]
ah-ha. Something definitely seems incorrect on the second refresh. I timed things this morning at work (using Chrome on my desktop) so that:

1. Logged in and then closed the page
2. Waited >1 hour for the token to expire
3. Loaded the page again and didn't have to login so the refresh token must have been used.
4. Waited >1 hour again for the new token to expire
5. Loaded the page again and was prompted for login

This at least better pinpoints where the problem is. I did double check to make sure I still have a valid eas session cookie and indeed I do and it's still the original session ID.

**Comment by travisghansen** [comment]
1. Do you have the logs to see which assertion failed triggering the 302?
1. Who is your provider?
1. Was the refresh token different after the initial refresh?
1. Does your refresh token expire?

I've seen situations where refresh tokens can only be used once. Also I've seen where refresh tokens have expiration time on them. It's a pretty nasty intersection of stuff here to debug :(

**Comment by kevinoconnor7** [comment]
Ah, you are correct.

1. The key detail here is the log entry `tokenSet is expired and refresh tokens disabled`. This should only happen if the token is expired and the cannot be refresh.
2. AWS Cognito
3. There was no `refresh_token` in the response
4. Yes, by default after 30 days.

I dug into the code in [AWS Amplify's Cognito implementation](https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1414) and found that copy the original `refresh_token`.

Searching around the spec seems to not be super clear here. The `refresh_token` is optional in the response but doesn't specify whether this means the original is still valid.

I think the best option here is to persist the original `refresh_token` if we haven't been provided a new one. Worst case it's not reusable and we just fail to refresh next time around. I open a PR (#45) to implement this.

**Comment by travisghansen** [comment]
Interesting, so we're blasting the old tokenSet in it's entirety wiping out the old refresh_token? Since a the new tokenSet doesn't include a refresh_token we've lost that ability on subsequent requests. Makes sense...at least in terms of what behvior you're seeing.

Did you test our your MR and did it resolve your issue?

**Comment by kevinoconnor7** [comment]
Yup, I added a bunch of logging to see the `tokenSet` before and after the refresh. That's how I discovered the missing property after the refresh.

I hacked up my local version to make it think that the tokens expire every 10 seconds and was indeed able to refresh multiple times without getting a 302.

**Comment by travisghansen** [comment]
Excellent. Any other properties/tokens we should consider as well (userinfo I think is stored separately from the token set)?

**Comment by travisghansen** [comment]
Also, does the tokenSet (not individual tokens) have an expires property before/after the refresh? I would be interested to know how that is impacted by your scenario.

**Comment by kevinoconnor7** [comment]
That's the only difference I noticed, and yes, userinfo is updated separately.

I considered just merging the new data on top of the existing data, but that's probably brittle. I looked at the spec for [Refreshing an Access Token](https://tools.ietf.org/html/rfc6749#section-6) and it's supposed to return a standard [Successful Response](https://tools.ietf.org/html/rfc6749#section-5.1) (if appropriate). Based on that basically everything is required except for `refresh_token`, `scope`, and `expires_in`. The last one doesn't make sense to persist and `scope` isn't used by eas anyway. So `refresh_token` is the only remaining one as unrecognized properties are supposed to be ignored.

And yes, my new `tokenSet` includes an updated expires property.

**Comment by travisghansen** [comment]
Yeah, we may not use stuff directly but end-user assertions may be in place which would use the other options. In any case, it seems like bad form for the providers to be omitting that data anyhow upon refresh so I'm not terribly worried about it for the time being.

So if I understand correctly, in your case the `tokenSet` before and after are structurally the same with the addition/manual handling of the `refresh_token`? Or is something else omitted after refresh in your scenario?

Generally the code seems like a sane approach (given the insane approach of the response from AWS). It's limited to scenarios where they already had a `refresh_token` AND it's still valid (or it would have attempted to refresh in the first place) so it's safe to assume it will be valid immediately following the refresh. As I mentioned some providers actually invalidate a refresh token after it has been used but there's not really any way for us to know that pre-emptively and it doesn't hurt much to try anyhow.

**Comment by kevinoconnor7** [comment]
Yes, your understanding is correct.

I'm not sure that the AWS response is that unreasonable. The [spec](https://tools.ietf.org/html/rfc6749#page-48) says:

>    The authorization server MAY issue a new refresh token, in which case
   the client MUST discard the old refresh token and replace it with the
   new refresh token.  The authorization server MAY revoke the old
   refresh token after issuing a new refresh token to the client.  If a
   new refresh token is issued, the refresh token scope MUST be
   identical to that of the refresh token included by the client in the
   request.

This is pretty open-ended, especially when paired with the [response spec](https://tools.ietf.org/html/rfc6749#page-44):

>    refresh_token
         OPTIONAL.  The refresh token, which can be used to obtain new
         access tokens using the same authorization grant as described
         in Section 6.

My read on this is that the client may issue a new `refresh_token` and may or may not revoke the old one -- that's it. Therefore I think valid cases are:

1. `refresh_token` is omitted and still valid
2. `refresh_token` is omitted and has been revoked
3. `refresh_token` is returned but it's the pre-existing one
4. `refresh_token` is returned but it's a new one and the old one is still valid
5. `refresh_token` is returned but it's a new one and the old one revoked

I would say (2) is the only debatable one since generally an implementation shouldn't arbitrarily revoke things unless told otherwise. But again, that isn't really covered.

My guess would be that AWS omitted the `refresh_token` because it didn't issue a new one. That's not totally unreasonable to me.

But oof -- this spec really could have used some more details. They left a lot as an exercise to the reader.

**Comment by travisghansen** [comment]
Yeah, thanks for sending that over. I'm mostly referring to the behavior of the others I've seen vs AWS and not necessarily the spec per-se.

I've rarely (if ever) seen 1 or 2. Generally I see 3, 4 or 5. In any case, let's get it merged and approach the situation pragmatically :) If a resultant issue comes up we'll address it.

Thanks so much for the feedback/input/contribution here! Greatly appreciated to get more eyes on this stuff.

**Comment by travisghansen** [comment]
New image is built.

**Comment by kevinoconnor7** [comment]
Deployed the new version this morning and so far it seems to be working! I'll close this issue for now.

**Comment by travisghansen** [comment]
Awesome! Thanks for digging into that one, that's a good find!
