### ISSUE TITLE
Feature request: disable encryption for server-side tokens

### ISSUE THREAD

**Issue by Subreptivus** [travisghansen/external-auth-server#46]
Hello,

First of all let me thank you for all your work and good product!

Do you have any plans to add an option to not use encryption on server-side tokens?

We're deploying our clusters quite frequently and encryption for tokens isn't always working for us. We're trying to avoid node scripts (for our own reasons), and were using openssl script at first, and python script currently. Rarely we have `digital envelope routines` errors, after token creation, hence the need of regenerating of tokens.
We're using only server-side tokens. Don't get me wrong, but I don't see much sense of using encryption on server-side tokens.

**Comment by travisghansen** [comment]
Thanks for the interest and kind words! Glad to hear you find the project useful. I had some specific reasons for requiring them to be encrypted even on the server-side but I'll have to dig through my notes to see if I can find them again. Generally I'm open to not requiring it though. I'll do some digging and then reach back out.

**Comment by travisghansen** [comment]
I don't seem to find anything in my notes about this. To be clear you want to store the `jwt` still though right...something that's been signed etc? ie: something that matches the regex here for example: https://www.regextester.com/105777

**Comment by Subreptivus** [comment]
It may not even be `jwt`, but just plain config. In any case, it would still be easier to have it without encryption as from perspective of adding it to configuration, as from application perspective to decrypt token every time it retrieves it from storage.

**Comment by travisghansen** [comment]
Yeah it has to be the actual `jwt` for sure. Otherwise signatures could not be checked and I don't think it would be good to have the app signing jwts either.

I've got some other PRs to review so I'll look into this one as well.

**Comment by travisghansen** [comment]
I've added this to the `next` branch. Can you try installing with that image tag and let me know how it goes?

**Comment by Subreptivus** [comment]
Thank you very much, I'm really appreciate it!
Works as intended.
I didn't even have to build docker image myself, everything is up by you.

**Comment by luozhihua** [comment]
@travisghansen It looks like server-side token encryption can be disabled on the next branch, but how should I configure it? My understanding is that you don't need to execute `node bin / generate-config-token.js` after installing the chart directly with helm. Is my understanding correct?

**Comment by travisghansen** [comment]
@luozhihua you still need to create a valid `jwt`. That script could be updated to also output the unencrypted `jwt` as well. Optionally you could use any tool of your liking to create the `jwt` just make sure you use the same signing key as `eas` is deployed with.

Short story is yes, you still need to create a token using some tool.
