### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by nenadalm** [travisghansen/external-auth-server#48]
Hi. I installed the server via helm and I am receiving the error from title after ldap login.

Version:
```
# helm -n auth-server list
NAME       	NAMESPACE  	REVISION	UPDATED                                	STATUS  	CHART                     	APP VERSION
auth-server	auth-server	3       	2020-01-15 10:12:52.779433674 +0100 CET	deployed	external-auth-server-0.1.0	1.0
```

Relevang logs:
```
{"service":"external-auth-server","level":"verbose","message":"ldap userinfo: undefined"}
{"level":"error","service":"external-auth-server","message":"Cannot read property 'data' of undefined","stack":"TypeError: Cannot read property 'data' of undefined\n    at LdapPlugin.verify (/home/eas/app/src/plugin/ldap/index.js:115:30)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"}
{"service":"external-auth-server","level":"info","message":"end verify pipeline with status: 503"}
```

maybe the check: https://github.com/travisghansen/external-auth-server/blob/c4d9bec302513511271f52dc6be887cb0c6e8f3c/src/plugin/ldap/index.js#L112

should be `userinfo != null` instead of `userinfo !== null`?

**Comment by nenadalm** [comment]
I've tried to change the condition to `userinfo != null` and now it looks like auth was maybe successful. Last log after login attempt:
```
{"service":"external-auth-server","level":"info","message":"end verify pipeline with status: 200"}
```

It doesn't seems to work with Traefik though as these are the logs from it:
```
10.244.0.1 - - [15/Jan/2020:10:00:47 +0000] "GET / HTTP/2.0" 401 0 "-" "-" 36 "logging-logging-kibana-tls-3dbeba1dfa30b0a6c13d@kubernetescrd" - 19ms
10.244.0.1 - - [15/Jan/2020:10:00:54 +0000] "GET / HTTP/2.0" 401 317 "-" "-" 37 "logging-logging-kibana-tls-3dbeba1dfa30b0a6c13d@kubernetescrd" "https://10.244.0.174:5601" 108ms
```
First request is the one where basic auth popup appears, second request happens when I try to login.

**Comment by nenadalm** [comment]
Traefik version: `v2.0.5`

**Comment by nenadalm** [comment]
So I found that it kind of works. I test it with Kibana.

### Expected behaviour

When forwardauth in Traefik is turned off it works as expected:
```
- I go to `/`
- I am redirected by 302 to `/login?next=%2F#?_g=()`
```

When forwardauth in Traefik is turned on I am able to login if there are no redirects:
```
- I go to `/login?next=%2F#?_g=()`
- I am asked to provide credentials
- I am still on `/login?next=%2F#?_g=()` logged in
```

### Unexpected behaviour

When forwardauth in Traefik is turned on I am unable to login if there are redirects:
```
- I go to `/`
- I am asked to provide credentials
- I am still on `/` with 401 response
```

This looks like maybe issue with Traefik?

**Comment by nenadalm** [comment]
So there seems to be only the issue with undefined property.

Other issue is caused by enabled basic authentication in Kibana. (Kibana received ldap credentials and these are not valid there).

I'll send pr fixing the condition.

**Comment by travisghansen** [comment]
Thanks for the contribution! I'll review after some sleep and we'll get it all fixed up for ya.

**Comment by travisghansen** [comment]
So is the value of the property `undefined` in your scenario? Changing that check seems odd for sure.

**Comment by travisghansen** [comment]
Actually, also let me know what cache backend you are using (or send over the helm details redacting sensitive info). My guess is that different cache'ing drivers are handling that differently unfortunately :( I use redis for example and I'm pretty sure it's returning `null` when there is no entry.

**Comment by nenadalm** [comment]
I didn't install redis or anything:

`$ helm -n auth-server get values auth-server`
```yaml
USER-SUPPLIED VALUES:
configTokenEncryptSecret: ***
configTokenSignSecret: ***
configTokens:
- ""
cookieEncryptSecret: ***
cookieSignSecret: ***
image:
  tag: mila # image with patched condition
issuerEncryptSecret: ***
issuerSignSecret: ***
logLevel: verbose
sessionEncryptSecret: ***```

**Comment by travisghansen** [comment]
Ok that must be the difference. Redis cache backend vs in memory and how they return data. I'll have a look and audit the rest of the code in the project for the same kind of issue.

Thanks!

**Comment by travisghansen** [comment]
Can you submit your MR to this repo?
