### ISSUE TITLE
Feature request: Password Credentials Flow

### ISSUE THREAD

**Issue by djbulsink** [travisghansen/external-auth-server#49]
Hi,

We like to implement EAS with oidc, because of it's flexibility. In our use case we have web-and and desktop-applications using webservices authenticated by EAS. 

Some desktop applications which don't support the Authorization Code Flow, but only basic Authentication . That's why we like to have the "Password credential Flow" supported. 

I would like to hear your thoughts on this?

If you're positive about it, I'll give it a try to implement it and create PR.

**Comment by travisghansen** [comment]
Thanks for reaching out! Can you send the doc to the flow you're describing? I'm not familiar with that flow.

Not sure if this is related here: https://github.com/travisghansen/external-auth-server/issues/34

**Comment by djbulsink** [comment]
De flow is described here:
* https://oauth.net/2/grant-types/password/
* https://developer.okta.com/blog/2018/06/29/what-is-the-oauth2-password-grant). 

Because the client is handling the user and password it should not be used in every type of client. That's why I like to disable the flow by default.

**Comment by travisghansen** [comment]
This is a bit of an anti pattern here but I'm open to more discussion.

Does your service provider not use jwt tokens?

**Comment by djbulsink** [comment]
I'll investigate the jwt-token option. If jwt won't work out I'll create a pull request.
