### ISSUE TITLE
Feature Request: Cookie settings (HttpOnly, Secure)

### ISSUE THREAD

**Issue by dannyyy** [travisghansen/external-auth-server#50]
Hi,

I'm using `external-auth-server` together with Kubernetes and Traefik v2.1. It's really simple to configure and use.

I had, actually still have one issue which took me hours to find out why it happens exactly.
In my case, I have Home-Assistant as the service which should be protected by `external-auth-server`. This application is a `progressive web app (PWA)` which means, it uses `service-worker` quite heavily.
So, each initial authentication process was working fine (clean browser or incognito tab), because there was no `Service Worker` in place. After an hour (the token expired), I get redirected to Google for another sign in. But this time the final cookie cannot be set or read and the requests ends in a `503-error`.

I guess the issue behind is that the two cookies'  set have the flag `httpOnly`. This disallows the `service-worker` from getting/setting the cookies. But I'm not absolutely sure whether this is the only problem. But if I tick the option `Bypass for network` in the Chrome debug tools, then everything is working fine.

Is there already such an option to configure which flags should be set by `external-auth-server`? If not, would this be a huge task? I know I will lose a bit of security by not setting this flag. But I don't see any other possibility. On the other hand, I'm not very experienced with `service-workers`.

Thank you.
Best Danny

**Comment by travisghansen** [comment]
Ah! Very interesting. Should be pretty easy to make it an option. I'll see what I can get together this week as I'm traveling.

**Comment by dannyyy** [comment]
No hurry, it's ready when it's ready ;)

Thank you for your efforts to try to continuously improve this project.

**Comment by travisghansen** [comment]
I've added new parameters (`cookie.httpOnly` and `cookie.secure`) to manage this, try it out and let me know how it goes. It's currently in the `next` image tag until I merge to master and/or tag.

https://github.com/travisghansen/external-auth-server/commit/9eb59c2d48a02b2c8dc8b63fda9aa5057743279a

**Comment by dannyyy** [comment]
Thank you very much. 
The setting has been applied on the session-cookie only. The csrf-cookie still have the original `httpOnly`-flag. But I'm not sure whether both of them should be affected of not.

Anyway for the session-cookie it works very well.

![image](https://user-images.githubusercontent.com/3018863/73678312-69223e00-46b8-11ea-8411-02c2d33f7a70.png)

**Comment by travisghansen** [comment]
Ah, very good. The csrf should be fine left as is. I actually used to delete it but ran into some weird edge cases where certain proxies can't cope with it.

Did is solve your issues with HA?

**Comment by mlushpenko** [comment]
https://www.troyhunt.com/promiscuous-cookies-and-their-impending-death-via-the-samesite-policy/ 

New chrome release is coming, so SameSite is also needed for single sign-on scenarios, was about to open an issue but found this one :) 

My colleague just added SameSite and Secure here https://github.com/travisghansen/external-auth-server/blob/af3ae4a462f1cb0281d57db868c51b95b961e6f2/src/plugin/oauth/index.js#L441 and in scrf cookie and seems to be working fine (maybe a bit more testing is needed, but initially looks good)

**Comment by dannyyy** [comment]
@travisghansen 
My issues is partially solved. For the desktop environments it's solved, either with Chrome as well as with other browser.

Mobile is another story. If I use Firefox on my Android mobile, then it's more or less solved. It still goes very often the extra way to re-authenticate on google, but no 503 errors. With Chrome it's still the same. The first hour is okey, with no redirects or errors. After that, all requests to HA get redirected to Google and after the auth process I get a 404.

In my opinion is something truly wring with HA. I heard from others which try use some kind of auth portal in front of HA, that it's mostly not working properly.

I will invest some more hours this weekend to solve it.

**Comment by travisghansen** [comment]
@mlushpenko do you have a branch somewhere I can review with your changes?

@dannyyy service-workers could be an interesting situation and may not mix too well. I'm interested to see where it goes. It's similar to a single page app...there are very specific requirements to make it a bullet-proof experience.

**Comment by mlushpenko** [comment]
@travisghansen  no branch, but here are the changes, you'll probably want to make it configurable.

```
diff --git a/src/plugin/oauth/index.js b/src/plugin/oauth/index.js
index b48632e..380121d 100644
--- a/src/plugin/oauth/index.js
+++ b/src/plugin/oauth/index.js
@@ -248,6 +248,8 @@ class BaseOauthPlugin extends BasePlugin {
             {
               expires: new Date(Date.now() + STATE_CSRF_COOKIE_EXPIRY * 1000),
               httpOnly: true, //kills js access
+              secure: true,
+              sameSite: 'none',
               signed: true
             }
           );
@@ -446,6 +448,8 @@ class BaseOauthPlugin extends BasePlugin {
          */
         expires: cookieExpiresAt ? new Date(cookieExpiresAt) : null,
         httpOnly: true, //kills js access
+        secure: true,
+        sameSite: 'none',
         signed: true
       });
```

**Comment by travisghansen** [comment]
Ok yeah. The next branch already makes it configurable for the non-csrf cookie. I'll add the sameSite in there as well and add config options for the csrf stuff as well as it appears needed.

**Comment by travisghansen** [comment]
Ok, full control for managing cookies (csrf/session) has landed in `next` including the ability to completely disable the use of `csrf` cookie. This includes the settings for `sameSite` with a default of `none` for now.

Any review that can be done would be great before I snap a new release and merge to `master`.

Details are visible in this commit: https://github.com/travisghansen/external-auth-server/commit/f614542b70a3eab549dd8d5540c1200ef9f33534

**Comment by kettenbach-it** [comment]
In my setup, the SameSite cookie doesn't get set.

The config is:

```
        "csrf_cookie": {},
        "cookie": {
          "domain": "mydomain.com",
          "httpOnly": true,
          "secure": true,
          "sameSite": "Lax"
        },
```

**Comment by travisghansen** [comment]
I'll test that config again. Are you sure you pulled the most recent `next` image?

**Comment by kettenbach-it** [comment]
Yes

```
volker@volkers-mbp ~/external-auth-server > git checkout next                                                                                                                                                    
Already on 'next'
Your branch is up to date with 'origin/next'.
volker@volkers-mbp ~/external-auth-server > git pull                                                                                                                                                             git:(next|)
Already up to date.
```

**Comment by travisghansen** [comment]
Are you checking the response in devtools? Here is what I see with your config above:

```
Set-Cookie: _eas_oauth_session=s%3Aa6311204-6ef1-4dbd-b144-16720b0994d3.znanrfRhPEyFcIwhML2DcEU2hgMRS9Uly%2FOKsTZW3ZU; Path=/; HttpOnly; SameSite=Lax
```

**Comment by kettenbach-it** [comment]
This is the response from eas after successful auth:

```
content-length: 0
date: Fri, 28 Feb 2020 15:46:55 GMT
location: https://mydomain.com/
set-cookie: _eas_oauth_session=s%3Ac8c54ec5-8540-4649-83e8-9294d4bdadd3.tVNnIBtmE%2FfDwU7uj7FwiTZ3dg9XcKlVq1i%2BMEPzo8Q; Domain=verivinum.com; Path=/; HttpOnly; Secure
status: 302
X-DNS-Prefetch-Control: off
x-powered-by: Express
```

It is relay weird.
Git is definitely up-to-date:

![image](https://user-images.githubusercontent.com/7711872/75563345-809bdf00-5a4a-11ea-9848-1aebe0c81a54.png)

**Comment by kettenbach-it** [comment]
After starting the latest version of the docker image, the SameSite Cookie works!
Good work and thank's a lot!

**Comment by travisghansen** [comment]
Nice!

**Comment by travisghansen** [comment]
This has landed in master/latest.
