### ISSUE TITLE
Cannot POST /oauth/callback

### ISSUE THREAD

**Issue by manuelcoppotelli** [travisghansen/external-auth-server#61]
Hi,

I am using your external-auth-server (OIDC plugin only) with NGINX and an IdP that, after login, execute a post to: `https://my.domain.com/oauth/callback?state=abc123&session_state=def567&code=my-code`

This call fails with error `400` and message

```
Cannot POST /oauth/callback
```

How can I solve this?

**Comment by kettenbach-it** [comment]
What is the value of `redirect_uri`in your config_token.
AFAIK it needs to be to the URL of eas, e.g. https://eas.domain.com/oauth/callback
Otherwise the idP will redirect to your service.
Make sure that the `redirect_uri` is in your allowed callback urls at the idP.

**Comment by kettenbach-it** [comment]
oops, a second before I did hit enter, the issue was closed.

**Comment by manuelcoppotelli** [comment]
Yes, my mistake

**Comment by manuelcoppotelli** [comment]
I have a more serious issue #62
