### ISSUE TITLE
Refresh token issues

### ISSUE THREAD

**Issue by mlushpenko** [travisghansen/external-auth-server#68]
Hi, Travis, it could totally be an issue on our side with some configuration, but perhaps you could validate our assumptions or spot some bug.

In EAS, we see a number of errors like this (wondering is it normal the decoded token is null, probably not):
```
{"service":"external-auth-server","level":"debug","message":"refresh_token \"ZwrKulkHValgKfaAl3NpsPUKu6GNoC-Zv8LE\""}
{"service":"external-auth-server","level":"debug","message":"refresh_token decoded null"}
```

Also, later on, we get this message:
```
{"message":"tokenSet not refreshed externally","level":"warn","service":"external-auth-server"}
```

And, finally:
```
{"code":"ETIMEDOUT","connect":true,"level":"error","service":"external-auth-server","message":"ETIMEDOUT","stack":"Error: ETIMEDOUT\n at Timeout._onTimeout (/home/eas/app/node_modules/request/request.js:849:19)\n at ontimeout (timers.js:436:11)\n at tryOnTimeout (timers.js:300:5)\n at listOnTimeout (timers.js:263:5)\n at Timer.processTimers (timers.js:223:10)"}

{"service":"external-auth-server","level":"info","message":"end verify pipeline with status: 401"}
```

So, initial assumption that we have intermittent connectivity issues to the identity server, so we get a timeout and then 401 from EAS. But those messages with refresh tokens are troubling as well.  Would you have any insight/ideas?

And could you confirm that timeout is related to the OIDC provider? Based on this https://github.com/travisghansen/external-auth-server/blob/14f0bc042454bc60838884e546919d9c4c87d82f/src/plugin/oauth/index.js#L752 and this line `//TODO: better logic here to detect invalid_grant, etc` I guess a bit of info is missing to figure out why the error is happening even though I see you are already doing some specific error checks here   
https://github.com/travisghansen/external-auth-server/blob/14f0bc042454bc60838884e546919d9c4c87d82f/src/plugin/oauth/index.js#L1105

And, looking through some issues with refresh_tokens that we could see from our identity server logs, I've found this potential [solution]( https://github.com/IdentityServer/IdentityServer4/issues/2883#issuecomment-457059870) where token usage is `OneTimeOnly` versus our current setting or `ReUse`:
![image](https://user-images.githubusercontent.com/2006610/77555641-c61bc280-6eb7-11ea-8580-2be447a387f2.png)

Hope that's not too much info, maybe it's just a timeout issue and everything else is irrelevant.

**Comment by travisghansen** [comment]
@mlushpenko thanks for all the info! So a couple notes:

- the `refresh_token decoded` line is fine. Some provider supply a `refresh_token` that is itself a `jwt`. The fact that your provider does not is perfectly fine.

- that timeout does indeed appear to be related to the request to the identity provider. I don't think I should be returning a `401` though in that scenario but rather a `503` so I'll do some testing on that front and clean that up.

- The combination of potential options with the providers is quite extensive so it's hard to say what make the most sense. The question of `OneTimeOnly` vs `ReUse` can be complex as well. If `OneTimeUse` is returning a **new** `refresh_token` then I think you're probably fine. If it does not, then `ReUse` would be desired for sure. This question is likely a completely separate issue from the timeout however.

**Comment by mlushpenko** [comment]
Thanks for your answers, Travis, we may do some more testing with the token options if we rule out timeout problems, I hope one of my colleagues will reply here later, it's my last day today at the company.

**Comment by travisghansen** [comment]
Yeah no problem! I'm sure we'll get them sorted out.
