### ISSUE TITLE
Question - do tokens have to be encrypted ?

### ISSUE THREAD

**Issue by cameronbraid** [travisghansen/external-auth-server#73]
HI,

Just wondering if token encryption is strictly necessary.

Is it so that you can safely send tokens over a http connection to the auth server, rather than forcing use of https ?

If that is the reason, then could it be possible to support unencrypted tokens when using https to talk to the auth server - in my case when using istio I can use mutual tls

**Comment by travisghansen** [comment]
Initially I wanted to make the app stateless. I also wanted the option for separation of duties (people creating the tokens not the same as those creating the ingresses for example). Also, the tokens generally have sensitive information in them such as oauth secrets or ldap auth details etc that you may not want the ingress creators to know/have.

Having said all of that, I eventually implemented server-side tokens which helps with most of the above but introduces `state` (even if in the form of simple env vars). I would highly recommend their use for many circumstances. Server-side tokens *can* be stored unencrypted in whatever store you choose.

**Comment by travisghansen** [comment]
Got what you need on this one? How’s everything working out so far?
