### ISSUE TITLE
Feature request - oidc assertions on access_token

### ISSUE THREAD

**Issue by cameronbraid** [travisghansen/external-auth-server#75]
I use keycloak for oidc and keycloak currently returns the realm roles in the access token

I would like to be able to assert that the realm roles contains a value

If I can only do this for the id_token, I will have to configure an additional mapper in keycloak for each client and map the realm roles into the id token

**Comment by cameronbraid** [comment]
I had a go at this https://github.com/travisghansen/external-auth-server/pull/76

**Comment by travisghansen** [comment]
I'm actually shocked this isn't in there already. Let me do some digging and get back to you. Related to this is my '1.0' changes I have planned which will make this kind of thing generic (not specific to individual plugins) and would definitely resolve this.

Regardless this needs to be available before those breaking changes happen so if it's not there I'll add it in some shape or form and snap a new release.

**Comment by travisghansen** [comment]
Sure enough! Thanks for the contribution! I think the reason I may have left this out initially per the spec `id_token` is the only token that *must* be a `jwt`. Many providers do `access_token` as `jwt` as well but it's not certain. I'll merge what you have and get it into my `next` branch, add some documentation and finally snap the next release.

**Comment by travisghansen** [comment]
Thanks for the contribution. Merged to master and `v0.9.0`.
