### ISSUE TITLE
Fallback option

### ISSUE THREAD

**Issue by runningman84** [travisghansen/external-auth-server#78]
Right now I use GitHub with oauth. In case of an internet outage or GitHub problem I would like to have a fallback to htpasswd or IP based auth.

Is this already possible?

**Comment by travisghansen** [comment]
Yeah the plugins are a pipeline. The first to pass let’s the request through. Make note if the backing service depends on headers etc from github userinfo or whatever things may not work as expected so you either need to reproduce those values/headers with the additional plugins or deal with the ramifications on the app side.

I for example run a pipeline where all `OPTIONS` requests are allowed. Then I use the pcb feature to check for the authorization header along with scheme and specifically target the ldap and jwt plugins as appropriate. If the header isn’t present then I fallback to oidc.

I can share an example config if it’s helpful.

**Comment by runningman84** [comment]
Yes an example would be helpful. Are you sure that if I cannot reach my oauth server it would just use another method? How long does it wait to reach the oauth server?

**Comment by travisghansen** [comment]
Depending on your needs I would probably put the htpasswd *before* the oauth plugin. It really depends on the experience you want.

I’m currently away from my desk for another day or so but when I get back I’ll send over the example.

**Comment by travisghansen** [comment]
Just getting back to things. Did you get this figured out or would a sample still help?

**Comment by runningman84** [comment]
From my point of view a htpasswd is not very usable if I get asked for htpasswd each time. In my case I only want to be asked if the oauth server is not reachable.

**Comment by travisghansen** [comment]
I'm guessing these services are being accessed by a browser then vs machine to machine stuff?

If you're using server-side tokens I suppose you could just manually flip stuff around as well which doesn't sound ideal..

**Comment by runningman84** [comment]
Yes my use case is quite simple in a case of an internet outage I still want to access my local oauth protected services using a browser.

**Comment by travisghansen** [comment]
Do you prefer to manually tweak the config using server-side tokens? Or do you want the single config to gracefully determine when github is down and transparently switch?

**Comment by runningman84** [comment]
I would like a transparent switch because my config is stored in GitHub and synced with flux. Once I cannot reach GitHub any change is difficult...

**Comment by runningman84** [comment]
BTW. GitHub had some outage a few days ago so this is not an edge use case at work we had similar problems...

**Comment by travisghansen** [comment]
What’s the error response returned by the plugin in your scenario when github is down?

**Comment by runningman84** [comment]
Hmm GitHub is either not reachable at all or throw 50x errors. I am not sure what the exact error in external auth server was

**Comment by travisghansen** [comment]
OK, next time you see it grab the logs so I can see what the response code is.

In general I've been thinking about this request a bit and it's a fairly complex scenario. I've been trying to come up with something that is designed well but haven't quite figured out a solution that seems great yet. I'll keep thinking..

**Comment by runningman84** [comment]
ok today there was a github outage:
```
curl -I https://github.com/login/oauth/authorize\?response_type\=code\&client_id\=xxx
HTTP/1.1 500 Internal Server Error
Server: GitHub.com
Date: Mon, 13 Jul 2020 07:44:57 GMT
Content-Type: text/html
Content-Length: 161248
ETag: "5f0b7868-275e0"
X-GitHub-Request-Id: 0513:7EA8:7FA2:E60D:5F0C10F9
X-Frame-Options: DENY
````

**Comment by travisghansen** [comment]
What was the response of the plugin in the eas logs?
