### ISSUE TITLE
gitlab provider

### ISSUE THREAD

**Issue by runningman84** [travisghansen/external-auth-server#83]
Is there any sample how to configure gitlab as a provider?

It looks like gitlab also uses team ids, it would be great if we could create a sample like this for gitlab:
https://github.com/travisghansen/external-auth-server/blob/master/contrib/generate-config-helm-traefik-github.js

**Comment by travisghansen** [comment]
I have an example somewhere and know it works generally with gitlab as I did testing against it. It is oauth and not oidc so we may need to put together a basic userinfo provider for extra information if needed.

As I recall the tokens are jwt but I don’t recall the extent of the info in there. I’ll do some basic testing and shoot over my findings.

**Comment by travisghansen** [comment]
OK, I lied gitlab does actually support `oidc`. The `id_token` has limited info that can be used for assertions, but it does support `userinfo` as well which includes the following (you may be able to add more with additional scopes, not sure...maybe the groups match what you're after for teams?):

```
{
  "iat": 1597423006,
  "data": {
    "sub": "1",
    "sub_legacy": "b7676e1d064ae88740e8895df2b5cd58529bacda446b22df3bf1f4a5d1044970",
    "name": "Travis Glenn Hansen",
    "nickname": "thansen",
    "email": "travisghansen@yahoo.com",
    "email_verified": true,
    "profile": "<redacted>",
    "picture": "https://secure.gravatar.com/avatar/fe873705633da34d0623cd88fd96d217?s=80&d=identicon",
    "groups": [
      "onegear",
      "devicetracker",
      "gentoo",
      "arch",
      "mirror"
    ]
  }
```

Here's the config token which produces the above:

```
    "aud": "development",
    "eas": {
      "plugins": [
        {
          "type": "oidc",
          "issuer": {
            "discover_url": "https://gitab.some.tld/.well-known/openid-configuration"
          },
          "client": {
            "client_id": "...",
            "client_secret": "..."
          },
          "scopes": ["openid", "email", "profile"],
          "redirect_uri": "http://localhost:9000/oauth/callback",
          "features": {
            "set_cookie_expiry": false,
            "refresh_access_token": true,
            "fetch_userinfo": true,
            "introspect_access_token": false,
            "authorization_token": "access_token"
          },
          "assertions": {
            "exp": true,
            "nbf": true,
            "iss": true,
            "userinfo": [],
            "id_token": []
          },
          "cookie": {}
        }
      ]
    }
```

**Comment by travisghansen** [comment]
Reopen if you need further info.

**Comment by runningman84** [comment]
Thanks for your example sorry that I haven't responded earlier

**Comment by kettenbach-it** [comment]
I can confirm this works on my site as well
