### ISSUE TITLE
extensions/v1beta1 Ingress is deprecated

### ISSUE THREAD

**Issue by bcha** [travisghansen/external-auth-server#86]
Came across this today while doing some updates:

```
  ==> Linting /tmp/914800423/external-auth-server/external-auth-server/travisghansen-external-auth-server/external-auth-server/~0.1.0/external-auth-server
  [INFO] Chart.yaml: icon is recommended
  [ERROR] templates/ingress.yaml: the kind "extensions/v1beta1 Ingress" is deprecated in favor of "networking.k8s.io/v1beta1 Ingress"
```

Appears to be hardcoded here:
https://github.com/travisghansen/external-auth-server/blob/301e47f261156cf22716c544d1e6d4ef84026c60/charts/external-auth-server/templates/ingress.yaml#L1-L5

**Comment by travisghansen** [comment]
There’s an MR to update but it’s updated to a hard-coded value as well.

I’ll add a conditional on it and publish a new chart.

**Comment by travisghansen** [comment]
Committed.
