### ISSUE TITLE
Support IDP initiated SLO

### ISSUE THREAD

**Issue by Ornias1993** [travisghansen/external-auth-server#87]
When using SSO with multiple different SP's/clients/apps/websites, that handle SSO themselves and/or have their own authentication that can't be bypassed, Single Logout (SLO) becomes a problem.

Both OIDC and SAML solved this problem by supporting (either in spec or in draft) IDP initiated SLO.
Once one of the SP's send a SLO request to the IDP, the IDP sends SLO requests for that session to all other SP's, all those other SP's should logout the user, which leads to all sessions being terminated server-side.

It does not seems this project currently can't handle logouts initiated by the IDP, it would be nice to see this feature added.

**Comment by travisghansen** [comment]
The specs around this seem quite complex and very specific to certain use cases. It would be helpful to narrow things down for expectations on this ticket to the relevant bits for how oidc is implemented in the project (authorization code flow).

A couple points:

- the project does currently support token introspection. If you have some way to invalidate the token with the idp/op then eas will destroy the session locally (if introspection is turned on)
- are you wanting eas to initiate slo? Or simply react to it when it has occurred out of band?
- can you read through this: https://medium.com/@robert.broeckelmann/openid-connect-logout-eccc73df758f and see which of the mechanisms make most sense here?

Reading through the medium article my initial impressions lead me to believe the relevant part would be in the section labeled ‘OP Initiated Logout with Back-Channel Communication’. Does that sound sane?

This is cool stuff. Happy to see where it goes!

**Comment by Ornias1993** [comment]
> Reading through the medium article my initial impressions lead me to believe the relevant part would be in the section labeled ‘OP Initiated Logout with Back-Channel Communication’. Does that sound sane?

Long things short: That sounds very sane, of all the methods I think thats the most solid one :)

**Comment by travisghansen** [comment]
Yeah ok, I’ll research that a bit more then. Is there a single endpoint that gets registered when you create the client in keycloak specifically? Or does the rp somehow send a specific endpoint on a per token basis when the workflow is initialized? I don’t recall seeing that when I dug into the workflow spec but could have missed it.

**Comment by Ornias1993** [comment]
It sends a logout request per-client.
so if you have one client for app-x and one client for app-y, you log out of app-x, keycloak should send the logout request to app-y too :)

**Comment by travisghansen** [comment]
Well, it sends the logout request for each token the user has with each client. I guess the question is, where/how is the logout url registered? Is it done manually in the keycloak admin ui once per client? Or can the rp ‘send’ it once per token?

**Comment by travisghansen** [comment]
https://openid.net/specs/openid-connect-backchannel-1_0.html

Appears to be once per client.

**Comment by travisghansen** [comment]
Just getting around to revisiting this, according to blogpost here: https://fixes.co.za/keycloak/keycloak-single-sign-out/ the endpoint that gets invoked is the `Admin URL` in the client configuration screen. However, I can't seem to get keycloak to invoke the URL. Anyone able to figure out the required combination of configuration to get keycloak to actually invoke the URL please let me know :)

**Comment by Ornias1993** [comment]
Did you try snooping the packages?

**Comment by travisghansen** [comment]
Not sure I follow that comment. I’ve figured out a way to manually trigger it via the UI where it does get invoked though but now I get failures with that as well.

If I use an http address it just fails (nothing in the logs but the ui says it failed), if I put an https address it gives the same failure in the ui but at least I get a log entry saying the java truststore isn’t configured.

**Comment by Ornias1993** [comment]
Yeah it requires HTTPS with valid certs...

**Comment by travisghansen** [comment]
Yeah if you figure out a magical combination I’ll work on it. I’ll keep trying some things on my end as well.

**Comment by travisghansen** [comment]
After much turmoil I’ve got the magical combination of options that allow the/a endpoint to be properly invoked. Maybe I can make some progress now :)

**Comment by Ornias1993** [comment]
Enlighten us ;-)

**Comment by travisghansen** [comment]
Gory details are in the linked issue above.

**Comment by travisghansen** [comment]
OK, I've fully implemented this functionality in `eas`...and more. I'll commit shortly after documenting everything but we now have support for:

- revoke tokens when logout initiated within `eas` (https://tools.ietf.org/html/rfc7009 (oauth2 and oidc))
- end the session with the provider when logout initiated within `eas` (https://openid.net/specs/openid-connect-rpinitiated-1_0.html)
- `backchannel_logout` support for logouts triggered at the provider (https://openid.net/specs/openid-connect-backchannel-1_0.html)

**Comment by travisghansen** [comment]
Released in `v0.10.0`.

https://github.com/travisghansen/external-auth-server/blob/master/OAUTH_PLUGINS.md#logout
