### ISSUE TITLE
release chart bump version

### ISSUE THREAD

**Issue by runningman84** [travisghansen/external-auth-server#88]
It looks like you have made some changes to the helm chart but the version is still 0.1.0. This causes issues if you try to update the chart because helm does not expect changes when the chart version stays the same. Please bump the chart version on each change to the chart...

**Comment by travisghansen** [comment]
Yeah, I'll manage that more tightly. I may move the chart to separate repo altogether at some point. I also just updated it to use the new location of the now deprecated 'stable' repo.

**Comment by travisghansen** [comment]
I bumped the version when I did that FYI so you should have the latest stuff now when you update.
