### ISSUE TITLE
Redis in Helm chart points to now invalid repository

### ISSUE THREAD

**Issue by CuBiC3D** [travisghansen/external-auth-server#90]
The Helm chart fails, because the Redis requirement points to the deprecated stable Helm repository which seems to no longer host the package.

```
could not download https://charts.helm.sh/stable/redis-ha-4.4.6.tgz: failed to fetch https://charts.helm.sh/stable/redis-ha-4.4.6.tgz : 404 Not Found
```

**Comment by travisghansen** [comment]
Ah, good point. I’ll fix it up by either pointing to the new location of the legacy repo or a compatible updated version somewhere.

**Comment by travisghansen** [comment]
Fixed.

**Comment by CuBiC3D** [comment]
Thank you!
