### ISSUE TITLE
Can I use Redis as config token store?

### ISSUE THREAD

**Issue by peadarDoyle** [travisghansen/external-auth-server#96]
As it says in the heading. Is it currently possible to use Redis as a config token store? From reading the documentation it seems like Redis is only currently used for sessions rather than for storing config tokens. Thus, if using the `config_token_store_id` that a dedicated store other than Redis needs to be created (i.e. a file, env var, or SQL db).

I ask since it would be convenient to also use Redis as a token store but there is no indication in the documentation that this is possible, or maybe it's obvious that it's possible and that is why it isn't documented? Since I'll be using the `oidc` plugin I need to have an instance of Redis in HA mode but thought I could avoid having to also add a SQL database to store config tokens by reusing Redis. 

Since I already have a Postgres server available it isn't much hassle to setup an additional database but thought I'd ask the question.

**Comment by travisghansen** [comment]
There’s no reason it couldn’t be added. You’d want to take care to make sure you deploy redis with stateful backing and configure it to write the state, otherwise I see no reason why it wouldn’t work.

**Comment by peadarDoyle** [comment]
So I went looking in the source code (which I should have done to begin with) and from that perspective it looks like this would involve creating a new redis adapter in `src/config_token_store/adapter/` that doesn't currently exist. Maybe I didn't explain well in my initial query but I was trying to pin down whether redis as a config token store was something already available out of the box.

As I said, I've got access to a SQL server so I think I will err on the side of already trodden ground. I'm already hacking together some Terraform scripts to put an eas db into my test environment.

Thanks for the prompt response.

**Comment by travisghansen** [comment]
Ok if the need arises just let me know. I’ve got some other tweaks I’ve been slowly working on and may add this just in the vein of completeness. Upcoming release will have greatly reduced image size and probably SLO with oidc providers.
